/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addItemFrame.java
 *
 * Created on Apr 15, 2012, 2:09:33 AM
 */
package ibuyswing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.StringTokenizer;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.session.WebAuthSession;
/**
 *
 * @author Luke
 */
public class addMenuFrame extends javax.swing.JFrame {

        private static DropboxAPI<WebAuthSession> mDBApi;
	private static String user;
        
    /** Creates new form addItemFrame */
    public addMenuFrame(String user, DropboxAPI<WebAuthSession> mDBApi) {
        
                super("iBuy - Add Item");
		this.user = user;
		this.mDBApi = mDBApi;
    
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newItemLabel = new javax.swing.JLabel();
        canceladdListButton = new javax.swing.JButton();
        addListButton = new javax.swing.JButton();
        newListTextField = new javax.swing.JTextField();
        menuNameLabel = new javax.swing.JLabel();
        instructionLabel = new javax.swing.JLabel();
        newListFeedBackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(addMenuFrame.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        newItemLabel.setFont(resourceMap.getFont("newItemLabel.font")); // NOI18N
        newItemLabel.setForeground(resourceMap.getColor("newItemLabel.foreground")); // NOI18N
        newItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newItemLabel.setText(resourceMap.getString("newItemLabel.text")); // NOI18N
        newItemLabel.setName("newItemLabel"); // NOI18N

        canceladdListButton.setBackground(resourceMap.getColor("canceladdListButton.background")); // NOI18N
        canceladdListButton.setFont(resourceMap.getFont("canceladdListButton.font")); // NOI18N
        canceladdListButton.setForeground(resourceMap.getColor("canceladdListButton.foreground")); // NOI18N
        canceladdListButton.setText(resourceMap.getString("canceladdListButton.text")); // NOI18N
        canceladdListButton.setActionCommand(resourceMap.getString("canceladdListButton.actionCommand")); // NOI18N
        canceladdListButton.setName("canceladdListButton"); // NOI18N
        canceladdListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceladdListButtonActionPerformed(evt);
            }
        });

        addListButton.setBackground(resourceMap.getColor("addListButton.background")); // NOI18N
        addListButton.setFont(resourceMap.getFont("addListButton.font")); // NOI18N
        addListButton.setForeground(resourceMap.getColor("addListButton.foreground")); // NOI18N
        addListButton.setText(resourceMap.getString("addListButton.text")); // NOI18N
        addListButton.setActionCommand(resourceMap.getString("addListButton.actionCommand")); // NOI18N
        addListButton.setName("addListButton"); // NOI18N
        addListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addListButtonActionPerformed(evt);
            }
        });

        newListTextField.setFont(resourceMap.getFont("newListTextField.font")); // NOI18N
        newListTextField.setName("newListTextField"); // NOI18N

        menuNameLabel.setFont(resourceMap.getFont("menuNameLabel.font")); // NOI18N
        menuNameLabel.setForeground(resourceMap.getColor("menuNameLabel.foreground")); // NOI18N
        menuNameLabel.setText(resourceMap.getString("menuNameLabel.text")); // NOI18N
        menuNameLabel.setName("menuNameLabel"); // NOI18N

        instructionLabel.setFont(resourceMap.getFont("instructionLabel.font")); // NOI18N
        instructionLabel.setForeground(resourceMap.getColor("instructionLabel.foreground")); // NOI18N
        instructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabel.setText(resourceMap.getString("instructionLabel.text")); // NOI18N
        instructionLabel.setName("instructionLabel"); // NOI18N

        newListFeedBackLabel.setFont(resourceMap.getFont("newListFeedBackLabel.font")); // NOI18N
        newListFeedBackLabel.setForeground(resourceMap.getColor("newListFeedBackLabel.foreground")); // NOI18N
        newListFeedBackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newListFeedBackLabel.setName("newListFeedBackLabel"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newItemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(instructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(menuNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newListTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newListFeedBackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(canceladdListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(instructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newListFeedBackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newListTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuNameLabel))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canceladdListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-344)/2, (screenSize.height-344)/2, 344, 344);
    }// </editor-fold>//GEN-END:initComponents

    private void addListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListButtonActionPerformed
        if(evt.getSource() == addListButton)
  		{
			addList();
  		}
    }//GEN-LAST:event_addListButtonActionPerformed

    private void canceladdListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceladdListButtonActionPerformed
        if(evt.getSource() == canceladdListButton)
  		{
			new mainMenuFrame(user, mDBApi);
  			setVisible(false);
  			dispose();
  		}
    }//GEN-LAST:event_canceladdListButtonActionPerformed
public void addList()
	{
		String listName = newListTextField.getText();
		if(listName.equals(""))
			newListFeedBackLabel.setText("Please Give List a Name");
		else
		{
			String listFile = Global.getFile(mDBApi, "/" + user + "/lists.txt");
			StringTokenizer st = new StringTokenizer(listFile);
            boolean isTaken = false;
            while(st.hasMoreTokens())
            {
            	if(st.nextToken().equals(Global.toFileName(listName)))
            	{
            		isTaken = true;
            		break;
            	}
            	st.nextToken();
            	st.nextToken();
            }
            if(isTaken)
            {
            	newListFeedBackLabel.setText("Name is taken");
            }
            else
            {
            	//Adds list to users list collection
            	listName = Global.toFileName(listName);
            	Date d = new Date(System.currentTimeMillis());
            	listFile += listName + "\t0.00\t" + Global.toFileName(d.toString()) + "\n";
            	Global.putFileOverwrite(mDBApi, "/" + user + "/lists.txt", listFile);
	        	
	        	//Creates new list
	        	Global.putFile(mDBApi, "/" + user + "/" + listName + ".txt", "");

	        	//Redirects to Main Menu
	        	new mainMenuFrame(user, mDBApi);
				setVisible(false);
	        	dispose();
            }
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addListButton;
    private javax.swing.JButton canceladdListButton;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menuNameLabel;
    private javax.swing.JLabel newItemLabel;
    private javax.swing.JLabel newListFeedBackLabel;
    private javax.swing.JTextField newListTextField;
    // End of variables declaration//GEN-END:variables
}
