/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * changeListName.java
 *
 * Created on Apr 21, 2012, 1:50:53 PM
 */
package ibuyswing;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.LinkedList;
import java.util.StringTokenizer;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.session.WebAuthSession;

/**
 *
 * @author Luke
 */
public class changeListName extends javax.swing.JFrame {

        private DropboxAPI<WebAuthSession> mDBApi;
	private String user, filename;
        
    /** Creates new form changeListName */
    public changeListName(String user, String filename, DropboxAPI<WebAuthSession> mDBApi) {
        
        super("iBuy - Change Menu");
	this.user = user;
	this.filename = filename;
	this.mDBApi = mDBApi; 
        initComponents();
        origionalListNameLabel.setText(filename);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeListPanel = new javax.swing.JPanel();
        listNameChangeLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        listNameField = new javax.swing.JTextField();
        origionalListNameLabel = new javax.swing.JLabel();
        currentListLabel = new javax.swing.JLabel();
        newListNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        changeListPanel.setBackground(new java.awt.Color(51, 51, 51));
        changeListPanel.setName("changeListPanel"); // NOI18N

        listNameChangeLabel.setFont(new java.awt.Font("Tahoma 36", 1, 24)); // NOI18N
        listNameChangeLabel.setForeground(new java.awt.Color(255, 153, 0));
        listNameChangeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listNameChangeLabel.setText("List Name Change:");
        listNameChangeLabel.setName("listNameChangeLabel"); // NOI18N

        cancelButton.setBackground(new java.awt.Color(102, 102, 102));
        cancelButton.setFont(new java.awt.Font("Tahoma 18 18 12 18", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setActionCommand("cancelAccountButton");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        confirmButton.setBackground(new java.awt.Color(102, 102, 102));
        confirmButton.setFont(new java.awt.Font("Tahoma 18 18 12 18", 1, 18)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.setActionCommand("cancelAccountButton");
        confirmButton.setName("confirmButton"); // NOI18N
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        listNameField.setName("listNameField"); // NOI18N

        origionalListNameLabel.setBackground(new java.awt.Color(51, 51, 51));
        origionalListNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        origionalListNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        origionalListNameLabel.setName("origionalListNameLabel"); // NOI18N

        currentListLabel.setBackground(new java.awt.Color(51, 51, 51));
        currentListLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        currentListLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentListLabel.setText("Current List:");
        currentListLabel.setName("currentListLabel"); // NOI18N

        newListNameLabel.setBackground(new java.awt.Color(51, 51, 51));
        newListNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newListNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        newListNameLabel.setText("New Name for List:");
        newListNameLabel.setName("newListNameLabel"); // NOI18N

        javax.swing.GroupLayout changeListPanelLayout = new javax.swing.GroupLayout(changeListPanel);
        changeListPanel.setLayout(changeListPanelLayout);
        changeListPanelLayout.setHorizontalGroup(
            changeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listNameChangeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(changeListPanelLayout.createSequentialGroup()
                        .addComponent(currentListLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(origionalListNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(changeListPanelLayout.createSequentialGroup()
                        .addGroup(changeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, changeListPanelLayout.createSequentialGroup()
                                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(changeListPanelLayout.createSequentialGroup()
                                .addComponent(newListNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
        );
        changeListPanelLayout.setVerticalGroup(
            changeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listNameChangeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origionalListNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(changeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newListNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(changeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changeListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changeListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-277)/2, (screenSize.height-268)/2, 277, 268);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if(evt.getSource() == cancelButton){
		
            new itemListView(user, filename, mDBApi);
            setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if(evt.getSource() == confirmButton)
		{
			String newName = listNameField.getText();
			
			//Checks if name is taken
			String listNames = Global.getFile(mDBApi, "/" + user + "/lists.txt");
			StringTokenizer scanner = new StringTokenizer(listNames);
			boolean isTaken = false;
			while(scanner.hasMoreTokens())
  			{
  				String listname = scanner.nextToken();
  				scanner.nextToken();
  				scanner.nextToken();
  				if(listname.equals(Global.toFileName(newName)))
  				{
  					isTaken = true;
  				}
  			}
			if(isTaken)
			{
				System.out.println("List name is taken.");
			}
			else
			{
				//Read contents of file and writes to new file
				String contents = Global.getFile(mDBApi, "/" + user + "/" + Global.toFileName(filename) + ".txt");
				Global.putFile(mDBApi, "/" + user + "/" + Global.toFileName(listNameField.getText()) + ".txt", contents);
				
				//Delete old file
				Global.delete(mDBApi, "/" + user + "/" + Global.toFileName(filename) + ".txt");
				
				//Finds filename in list and changes it
				StringTokenizer st = new StringTokenizer(Global.getFile(mDBApi, "/" + user + "/lists.txt"));
				String newList = "";
				while(st.hasMoreTokens())
				{
					String token = st.nextToken();
					String token2 = st.nextToken();
					String token3 = st.nextToken();
					if(token.equals(Global.toFileName(filename)))
					{
						Date d = new Date(System.currentTimeMillis());
						newList += Global.toFileName(newName) + "\t" + token2 + "\t" + Global.toFileName(d.toString())  + "\n";
					}
					else
						newList += token + "\t" + token2 + "\t" + token3 + "\n";
				}
				Global.putFileOverwrite(mDBApi, "/" + user + "/lists.txt", newList);
				
				//Returns to List
				new addItemFrame(user, newName, mDBApi);
				setVisible(false);
				dispose();
			}
		}
    }//GEN-LAST:event_confirmButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel changeListPanel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel currentListLabel;
    private javax.swing.JLabel listNameChangeLabel;
    private javax.swing.JTextField listNameField;
    private javax.swing.JLabel newListNameLabel;
    private javax.swing.JLabel origionalListNameLabel;
    // End of variables declaration//GEN-END:variables
}
