/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * deleteListFrame.java
 *
 * Created on Apr 15, 2012, 12:38:36 AM
 */
package ibuyswing;

import java.util.LinkedList;
import java.util.StringTokenizer;

import javax.swing.JButton;
import java.awt.ScrollPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.GridLayout;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.exception.DropboxException;
import com.dropbox.client2.session.AccessTokenPair;
import com.dropbox.client2.session.AppKeyPair;
import com.dropbox.client2.session.WebAuthSession;

/**
 *
 * @author Luke
 */

public class deleteListFrame extends javax.swing.JFrame implements ActionListener {

    private static DropboxAPI<WebAuthSession> mDBApi;
    private LinkedList<JButton> list = new LinkedList<JButton>();
    private static String user;
    
    /** Creates new form deleteListFrame */
    public deleteListFrame(String user, DropboxAPI<WebAuthSession> mDBApi) {
        
        super("iBuy - Delete List");
        this.user = user;
	this.mDBApi = mDBApi;
        initComponents();
        getList();
    }
        
        public final void getList(){
        list.clear();
	    StringTokenizer st = new StringTokenizer(Global.getFile(mDBApi, "/"+user+"/lists.txt"));
		while(st.hasMoreTokens())
		{
			JButton j = new JButton(Global.readFileName(st.nextToken()));
			st.nextToken();
                        String nextToken = st.nextToken();
			j.addActionListener(this);
			list.add(j);
		}
		setLayout(new GridLayout(list.size()+1,1));
                setSize(500, Math.min((200 + 100*list.size()), 1000));
		for(int i = 0; i < list.size(); i++)
		{
		    listScrollPane.add(list.get(i));
		}
       	
	    setContentPane(listScrollPane);
        setVisible(true);
	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteListPanel = new javax.swing.JPanel();
        newListLabel = new javax.swing.JLabel();
        cancelListButton = new javax.swing.JButton();
        listScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(deleteListFrame.class);
        deleteListPanel.setBackground(resourceMap.getColor("deleteListPanel.background")); // NOI18N
        deleteListPanel.setName("deleteListPanel"); // NOI18N

        newListLabel.setFont(resourceMap.getFont("newListLabel.font")); // NOI18N
        newListLabel.setForeground(resourceMap.getColor("newListLabel.foreground")); // NOI18N
        newListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newListLabel.setText(resourceMap.getString("newListLabel.text")); // NOI18N
        newListLabel.setName("newListLabel"); // NOI18N

        cancelListButton.setBackground(resourceMap.getColor("cancelListButton.background")); // NOI18N
        cancelListButton.setFont(resourceMap.getFont("cancelListButton.font")); // NOI18N
        cancelListButton.setForeground(resourceMap.getColor("cancelListButton.foreground")); // NOI18N
        cancelListButton.setText(resourceMap.getString("cancelListButton.text")); // NOI18N
        cancelListButton.setActionCommand(resourceMap.getString("cancelListButton.actionCommand")); // NOI18N
        cancelListButton.setName("cancelListButton"); // NOI18N
        cancelListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelListButtonActionPerformed(evt);
            }
        });

        listScrollPane.setName("listScrollPane"); // NOI18N

        javax.swing.GroupLayout deleteListPanelLayout = new javax.swing.GroupLayout(deleteListPanel);
        deleteListPanel.setLayout(deleteListPanelLayout);
        deleteListPanelLayout.setHorizontalGroup(
            deleteListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteListPanelLayout.createSequentialGroup()
                        .addGroup(deleteListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteListPanelLayout.createSequentialGroup()
                                .addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteListPanelLayout.createSequentialGroup()
                                .addComponent(cancelListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        deleteListPanelLayout.setVerticalGroup(
            deleteListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteListPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-345)/2, (screenSize.height-289)/2, 345, 289);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelListButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == cancelListButton)
		{
			dispose();
		}
    }//GEN-LAST:event_cancelListButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelListButton;
    private javax.swing.JPanel deleteListPanel;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JLabel newListLabel;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
