/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainMenuFrame.java
 *
 * Created on Apr 16, 2012, 11:40:09 AM
 */
package ibuyswing;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayOutputStream;
import java.util.LinkedList;
import java.util.StringTokenizer;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.awt.CardLayout;
import javax.swing.ScrollPaneLayout;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.session.WebAuthSession;

/**
 *
 * @author Luke
 */
public class mainMenuFrame extends javax.swing.JFrame implements ActionListener{

    private static DropboxAPI<WebAuthSession> mDBApi;
    private LinkedList<JButton> list = new LinkedList<JButton>(); 
    private String user;
    
    
    /** Creates new form mainMenuFrame */
    public mainMenuFrame(String user, DropboxAPI<WebAuthSession> mDBApi) {
        super("Ibuy-Main Menu");
        
        this.user = user;
	this.mDBApi = mDBApi;
            
        initComponents();
        StringTokenizer st = new StringTokenizer(Global.getFile(mDBApi, "/"+user+"/lists.txt"));
	    list.clear();
		while(st.hasMoreTokens())
		{
			JButton j = new JButton(Global.readFileName(st.nextToken()));
			st.nextToken();
			st.nextToken();
			j.addActionListener(this);
			list.add(j);
		}
		
		//Sets layout with list size in mind
            
		setLayout(new GridLayout(list.size()+5,1));
		setSize(500, Math.min((200 + 100*list.size()), 1000));
		
		for(int i = 0; i < list.size(); i++)
		{
		    scrollPane1.add(list.get(i));
		}
        
        
            
	    //setVisible(true);           
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainMenuPanel = new javax.swing.JPanel();
        MainMenuLabel = new javax.swing.JLabel();
        refreshButton1 = new javax.swing.JButton();
        addListButton = new javax.swing.JButton();
        deleteList1 = new javax.swing.JButton();
        optionsButton1 = new javax.swing.JButton();
        logOutButton1 = new javax.swing.JButton();
        viewListButton = new javax.swing.JButton();
        listLabelMainMenu = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setName("mainPanel"); // NOI18N

        mainMenuPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainMenuPanel.setName("mainMenuPanel"); // NOI18N

        MainMenuLabel.setFont(new java.awt.Font("Tahoma 36", 1, 36));
        MainMenuLabel.setForeground(new java.awt.Color(255, 102, 0));
        MainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainMenuLabel.setText("Main Menu");
        MainMenuLabel.setName("MainMenuLabel"); // NOI18N

        refreshButton1.setBackground(new java.awt.Color(102, 102, 102));
        refreshButton1.setFont(new java.awt.Font("Tahoma 18", 1, 18));
        refreshButton1.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton1.setText("Refresh");
        refreshButton1.setName("refreshButton1"); // NOI18N
        refreshButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton1ActionPerformed(evt);
            }
        });

        addListButton.setBackground(new java.awt.Color(102, 102, 102));
        addListButton.setFont(new java.awt.Font("Tahoma 18", 1, 18));
        addListButton.setForeground(new java.awt.Color(255, 255, 255));
        addListButton.setText("Add List");
        addListButton.setName("addListButton"); // NOI18N
        addListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addListButtonActionPerformed(evt);
            }
        });

        deleteList1.setBackground(new java.awt.Color(102, 102, 102));
        deleteList1.setFont(new java.awt.Font("Tahoma 18", 1, 18));
        deleteList1.setForeground(new java.awt.Color(255, 255, 255));
        deleteList1.setText("Delete List");
        deleteList1.setName("deleteList1"); // NOI18N
        deleteList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteList1ActionPerformed(evt);
            }
        });

        optionsButton1.setBackground(new java.awt.Color(102, 102, 102));
        optionsButton1.setFont(new java.awt.Font("Tahoma 18", 1, 18));
        optionsButton1.setForeground(new java.awt.Color(255, 255, 255));
        optionsButton1.setText("Options");
        optionsButton1.setName("optionsButton1"); // NOI18N
        optionsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsButton1ActionPerformed(evt);
            }
        });

        logOutButton1.setBackground(new java.awt.Color(102, 102, 102));
        logOutButton1.setFont(new java.awt.Font("Tahoma 18", 1, 18));
        logOutButton1.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton1.setText("Log Out");
        logOutButton1.setName("logOutButton1"); // NOI18N
        logOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButton1ActionPerformed(evt);
            }
        });

        viewListButton.setBackground(new java.awt.Color(102, 102, 102));
        viewListButton.setFont(new java.awt.Font("Tahoma 18 18", 1, 18));
        viewListButton.setForeground(new java.awt.Color(255, 255, 255));
        viewListButton.setText("View List");
        viewListButton.setName("viewListButton"); // NOI18N
        viewListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListButtonActionPerformed(evt);
            }
        });

        listLabelMainMenu.setFont(new java.awt.Font("Tahoma", 1, 36));
        listLabelMainMenu.setForeground(new java.awt.Color(255, 102, 0));
        listLabelMainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listLabelMainMenu.setText("Lists:");
        listLabelMainMenu.setName("listLabelMainMenu"); // NOI18N

        scrollPane1.setName("scrollPane1"); // NOI18N

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addComponent(logOutButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listLabelMainMenu)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optionsButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteList1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addListButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewListButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addComponent(refreshButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listLabelMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addComponent(deleteList1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optionsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(logOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-768)/2, (screenSize.height-482)/2, 768, 482);
    }// </editor-fold>//GEN-END:initComponents

    private void addListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListButtonActionPerformed
        if(evt.getSource() == addListButton){
			new addListFrame(user, mDBApi);
			setVisible(true);
		}
    }//GEN-LAST:event_addListButtonActionPerformed

    private void deleteList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteList1ActionPerformed
            if(evt.getSource() == deleteList1){
			new deleteListFrame(user, mDBApi);
			setVisible(false);
		}
    }//GEN-LAST:event_deleteList1ActionPerformed

        private void optionsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsButton1ActionPerformed
            if (evt.getSource() == optionsButton1) { 
                new reportOptionsFrame(user, mDBApi).setVisible(true);
            }           
    }//GEN-LAST:event_optionsButton1ActionPerformed

    private void logOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButton1ActionPerformed
        if (evt.getSource() == logOutButton1) {   
            System.exit(0);
        }          
    }//GEN-LAST:event_logOutButton1ActionPerformed

    private void viewListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListButtonActionPerformed
        if (evt.getSource() == viewListButton) {            
                  new itemListView(user, filename, mDBApi);
        }    
    }//GEN-LAST:event_viewListButtonActionPerformed

    private void refreshButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton1ActionPerformed
        if(evt.getSource() == refreshButton1)
		{
			new mainMenuFrame(user, mDBApi);
			setVisible(false);
			dispose();
		}
    }//GEN-LAST:event_refreshButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainMenuLabel;
    private javax.swing.JButton addListButton;
    private javax.swing.JButton deleteList1;
    private javax.swing.JLabel listLabelMainMenu;
    private javax.swing.JButton logOutButton1;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton optionsButton1;
    private javax.swing.JButton refreshButton1;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JButton viewListButton;
    // End of variables declaration//GEN-END:variables

    private String filename;
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
