/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reportOptionsFrame.java
 *
 * Created on Apr 15, 2012, 3:44:38 PM
 */
package ibuyswing;

import java.awt.Checkbox;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import java.util.StringTokenizer;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.session.WebAuthSession;
/**
 *
 * @author Luke
 */
public class reportOptionsFrame extends javax.swing.JFrame {

        private static DropboxAPI<WebAuthSession> mDBApi;
	private LinkedList<JButton> list = new LinkedList<JButton>();
	private JCheckBox itemStatistics = new JCheckBox();
	private JCheckBox expenseTracker = new JCheckBox();
	private JCheckBox byWeek = new JCheckBox();
	private JCheckBox byLastTrip = new JCheckBox();
	private static String user;
        
    /** Creates new form reportOptionsFrame */
    public reportOptionsFrame(String user, DropboxAPI<WebAuthSession> mDBApi) {
        super("Options Menu");
    
        initComponents();
  
		this.user = user;
		this.mDBApi = mDBApi;
	
		StringTokenizer st = new StringTokenizer(new String(Global.getFile(mDBApi, "/" + user + "/report.txt")));
		while(st.hasMoreTokens())
		{
			String token = st.nextToken();
			if(token.equals("true"))
				itemStatistics.setSelected(true);
			token = st.nextToken();
			if(token.equals("true"))
				expenseTracker.setSelected(true);
			token = st.nextToken();
			if(token.equals("true"))
				byWeek.setSelected(true);
			token = st.nextToken();
			if(token.equals("true"))
				byLastTrip.setSelected(true);
                }
		optionsPanel.setLayout(new GridLayout(4,2));
		optionsPanel.add(itemStatistics);
		optionsPanel.add(new JTextField("Item Statistics"));
		optionsPanel.add(expenseTracker);
		optionsPanel.add(new JTextField("Expense Tracker"));
		optionsPanel.add(byWeek);
		optionsPanel.add(new JTextField("By Week"));
		optionsPanel.add(byLastTrip);
		optionsPanel.add(new JTextField("By Last Trip"));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportOptionsPanel = new javax.swing.JPanel();
        reportOptionsLabel = new javax.swing.JLabel();
        optionReturnButton = new javax.swing.JButton();
        optionsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(reportOptionsFrame.class);
        reportOptionsPanel.setBackground(resourceMap.getColor("reportOptionsPanel.background")); // NOI18N
        reportOptionsPanel.setName("reportOptionsPanel"); // NOI18N

        reportOptionsLabel.setFont(resourceMap.getFont("reportOptionsLabel.font")); // NOI18N
        reportOptionsLabel.setForeground(resourceMap.getColor("reportOptionsLabel.foreground")); // NOI18N
        reportOptionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportOptionsLabel.setText(resourceMap.getString("reportOptionsLabel.text")); // NOI18N
        reportOptionsLabel.setName("reportOptionsLabel"); // NOI18N

        optionReturnButton.setBackground(resourceMap.getColor("optionReturnButton.background")); // NOI18N
        optionReturnButton.setFont(resourceMap.getFont("optionReturnButton.font")); // NOI18N
        optionReturnButton.setForeground(resourceMap.getColor("optionReturnButton.foreground")); // NOI18N
        optionReturnButton.setText(resourceMap.getString("optionReturnButton.text")); // NOI18N
        optionReturnButton.setActionCommand(resourceMap.getString("optionReturnButton.actionCommand")); // NOI18N
        optionReturnButton.setName("optionReturnButton"); // NOI18N
        optionReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionReturnButtonActionPerformed(evt);
            }
        });

        optionsPanel.setName("optionsPanel"); // NOI18N

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout reportOptionsPanelLayout = new javax.swing.GroupLayout(reportOptionsPanel);
        reportOptionsPanel.setLayout(reportOptionsPanelLayout);
        reportOptionsPanelLayout.setHorizontalGroup(
            reportOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportOptionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(reportOptionsPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(reportOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionReturnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        reportOptionsPanelLayout.setVerticalGroup(
            reportOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportOptionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(optionReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(reportOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(reportOptionsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionReturnButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == optionReturnButton)
		{
			String newReport = "";
			if(itemStatistics.isSelected())
				newReport += "true\t";
			else
				newReport += "false\t";
			if(expenseTracker.isSelected())
				newReport += "true\t";
			else
				newReport += "false\t";
			if(byWeek.isSelected())
				newReport += "true\t";
			else
				newReport += "false\t";
			if(byLastTrip.isSelected())
				newReport += "true\t";
			else
				newReport += "false\t";
			Global.putFileOverwrite(mDBApi, "/" + user + "/report.txt", newReport);
			//new MainMenu(user, mDBApi);
			//setVisible(false);
			dispose();
		}
    }//GEN-LAST:event_optionReturnButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton optionReturnButton;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JLabel reportOptionsLabel;
    private javax.swing.JPanel reportOptionsPanel;
    // End of variables declaration//GEN-END:variables
}
