/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addItemFrame.java
 *
 * Created on Apr 15, 2012, 2:09:33 AM
 */
package ibuyswing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.StringTokenizer;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.session.WebAuthSession;
import javax.swing.JOptionPane;
/**
 *
 * @author Luke Tytor
 * @author Nicolas Pallares
 */
public class addItemFrame extends javax.swing.JFrame implements ActionListener{

        private static DropboxAPI<WebAuthSession> mDBApi;
	private static String user, filename;
        
    /** Creates new form addItemFrame */
    public addItemFrame(String user, String filename, DropboxAPI<WebAuthSession> mDBApi) {
        
                super("iBuy - Add Item");
		this.user = user;
		this.filename = filename;
		this.mDBApi = mDBApi;
    
        initComponents();
        jRadioButton1.setSelected(true);
        setVisible(true);
    }
    public String getSelected(){
    
        if(jRadioButton1.isSelected())
            return jRadioButton1.getText();
        if(jRadioButton2.isSelected())
            return jRadioButton2.getText();
        if(jRadioButton3.isSelected())
            return jRadioButton3.getText();
        if(jRadioButton4.isSelected())
            return jRadioButton4.getText();
        if(jRadioButton5.isSelected())
            return jRadioButton5.getText();
        return "";
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        addItemPanel = new javax.swing.JPanel();
        newItemLabel = new javax.swing.JLabel();
        canceladdItemButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        itemNameLabel = new javax.swing.JLabel();
        instructionLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        categoryField = new javax.swing.JTextField();
        storeLabel = new javax.swing.JLabel();
        storeField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(addItemFrame.class);
        addItemPanel.setBackground(resourceMap.getColor("addItemPanel.background")); // NOI18N
        addItemPanel.setForeground(resourceMap.getColor("addItemPanel.foreground")); // NOI18N
        addItemPanel.setName("addItemPanel"); // NOI18N

        newItemLabel.setFont(resourceMap.getFont("newItemLabel.font")); // NOI18N
        newItemLabel.setForeground(resourceMap.getColor("newItemLabel.foreground")); // NOI18N
        newItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newItemLabel.setText(resourceMap.getString("newItemLabel.text")); // NOI18N
        newItemLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newItemLabel.setName("newItemLabel"); // NOI18N

        canceladdItemButton.setBackground(resourceMap.getColor("canceladdItemButton.background")); // NOI18N
        canceladdItemButton.setFont(resourceMap.getFont("canceladdItemButton.font")); // NOI18N
        canceladdItemButton.setForeground(resourceMap.getColor("canceladdItemButton.foreground")); // NOI18N
        canceladdItemButton.setText(resourceMap.getString("canceladdItemButton.text")); // NOI18N
        canceladdItemButton.setActionCommand(resourceMap.getString("canceladdItemButton.actionCommand")); // NOI18N
        canceladdItemButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        canceladdItemButton.setName("canceladdItemButton"); // NOI18N
        canceladdItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceladdItemButtonActionPerformed(evt);
            }
        });

        addItemButton.setBackground(resourceMap.getColor("addItemButton.background")); // NOI18N
        addItemButton.setFont(resourceMap.getFont("addItemButton.font")); // NOI18N
        addItemButton.setForeground(resourceMap.getColor("addItemButton.foreground")); // NOI18N
        addItemButton.setText(resourceMap.getString("addItemButton.text")); // NOI18N
        addItemButton.setActionCommand(resourceMap.getString("addItemButton.actionCommand")); // NOI18N
        addItemButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        addItemButton.setName("addItemButton"); // NOI18N
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        nameField.setFont(resourceMap.getFont("nameField.font")); // NOI18N
        nameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nameField.setName("nameField"); // NOI18N

        itemNameLabel.setFont(resourceMap.getFont("itemNameLabel.font")); // NOI18N
        itemNameLabel.setForeground(resourceMap.getColor("itemNameLabel.foreground")); // NOI18N
        itemNameLabel.setText(resourceMap.getString("itemNameLabel.text")); // NOI18N
        itemNameLabel.setName("itemNameLabel"); // NOI18N

        instructionLabel.setFont(resourceMap.getFont("instructionLabel.font")); // NOI18N
        instructionLabel.setForeground(resourceMap.getColor("instructionLabel.foreground")); // NOI18N
        instructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabel.setText(resourceMap.getString("instructionLabel.text")); // NOI18N
        instructionLabel.setName("instructionLabel"); // NOI18N

        categoryLabel.setFont(resourceMap.getFont("categoryLabel.font")); // NOI18N
        categoryLabel.setForeground(resourceMap.getColor("categoryLabel.foreground")); // NOI18N
        categoryLabel.setText(resourceMap.getString("categoryLabel.text")); // NOI18N
        categoryLabel.setName("categoryLabel"); // NOI18N

        categoryField.setFont(resourceMap.getFont("categoryField.font")); // NOI18N
        categoryField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        categoryField.setName("categoryField"); // NOI18N

        storeLabel.setFont(resourceMap.getFont("storeLabel.font")); // NOI18N
        storeLabel.setForeground(resourceMap.getColor("storeLabel.foreground")); // NOI18N
        storeLabel.setText(resourceMap.getString("storeLabel.text")); // NOI18N
        storeLabel.setName("storeLabel"); // NOI18N

        storeField.setFont(resourceMap.getFont("storeField.font")); // NOI18N
        storeField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        storeField.setName("storeField"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jRadioButton1.setBackground(resourceMap.getColor("jRadioButton1.background")); // NOI18N
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(resourceMap.getColor("jRadioButton1.foreground")); // NOI18N
        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jRadioButton2.setBackground(resourceMap.getColor("jRadioButton2.background")); // NOI18N
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(resourceMap.getColor("jRadioButton2.foreground")); // NOI18N
        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N

        jRadioButton3.setBackground(resourceMap.getColor("jRadioButton3.background")); // NOI18N
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(resourceMap.getColor("jRadioButton3.foreground")); // NOI18N
        jRadioButton3.setText(resourceMap.getString("jRadioButton3.text")); // NOI18N
        jRadioButton3.setName("jRadioButton3"); // NOI18N

        jRadioButton4.setBackground(resourceMap.getColor("jRadioButton4.background")); // NOI18N
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setForeground(resourceMap.getColor("jRadioButton4.foreground")); // NOI18N
        jRadioButton4.setText(resourceMap.getString("jRadioButton4.text")); // NOI18N
        jRadioButton4.setName("jRadioButton4"); // NOI18N

        jRadioButton5.setBackground(resourceMap.getColor("jRadioButton5.background")); // NOI18N
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setForeground(resourceMap.getColor("jRadioButton5.foreground")); // NOI18N
        jRadioButton5.setText(resourceMap.getString("jRadioButton5.text")); // NOI18N
        jRadioButton5.setName("jRadioButton5"); // NOI18N

        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addItemPanelLayout = new javax.swing.GroupLayout(addItemPanel);
        addItemPanel.setLayout(addItemPanelLayout);
        addItemPanelLayout.setHorizontalGroup(
            addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemPanelLayout.createSequentialGroup()
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newItemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(canceladdItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addItemPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addItemPanelLayout.createSequentialGroup()
                                .addComponent(storeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(storeField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addItemPanelLayout.createSequentialGroup()
                                .addComponent(categoryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addItemPanelLayout.createSequentialGroup()
                                .addComponent(itemNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addItemPanelLayout.createSequentialGroup()
                                .addComponent(instructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(addItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addItemPanelLayout.setVerticalGroup(
            addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(instructionLabel)
                .addGap(26, 26, 26)
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(storeLabel))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canceladdItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addItemPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-344)/2, (screenSize.height-376)/2, 344, 376);
    }// </editor-fold>//GEN-END:initComponents

    private void canceladdItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceladdItemButtonActionPerformed
                 if(evt.getSource() == canceladdItemButton)
  		{
                    new itemListView(user, filename, mDBApi);                          
                    setVisible(false);
                    dispose();
  		}
    }//GEN-LAST:event_canceladdItemButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        if(evt.getSource() == addItemButton)
  		{
                        
			String name = Global.toFileName(nameField.getText());
			String category = Global.toFileName(categoryField.getText());
			String store = Global.toFileName(storeField.getText());
			//String importance = importanceField.getText();
                        //boolean isChecked = item.
                       
  			if(nameField.equals("") || categoryField.equals("") || store.equals(""))
  				JOptionPane.showMessageDialog(this, "Please complete all fields.");
  			else
  			{
  				//Append item parameters to end of list
  				String list = Global.getFile(mDBApi, "/" + user + "/" + Global.toFileName(filename) + ".txt");
  				StringTokenizer st2 = new StringTokenizer(list);
                                boolean okay = true;
				while(st2.hasMoreTokens())
				{
					String token = Global.readFileName(st2.nextToken());
					String token2 = st2.nextToken();
					String token3 = st2.nextToken();
                                        String token4 = st2.nextToken();
					String token5 = st2.nextToken();
					if(token.equals(name))
					{
                                            okay = false;
					}
				}
                                if(okay)
                                {
                                    list += name + "\t" + category + "\t" + store + "\t" + getSelected() + "\tfalse\n";
                                    Global.putFileOverwrite(mDBApi, "/" + user + "/" + Global.toFileName(filename) + ".txt", list);

                                    //Update list date
                                    StringTokenizer st = new StringTokenizer(Global.getFile(mDBApi, "/" + user + "/lists.txt"));
                                    String newList = "";
                                    while(st.hasMoreTokens())
                                    {
                                            String token = st.nextToken();
                                            String token2 = st.nextToken();
                                            String token3 = st.nextToken();
                                            if(token.equals(Global.toFileName(filename)))
                                            {
                                                    Date d = new Date(System.currentTimeMillis());
                                                    newList += token + "\t" + token2 + "\t" + Global.toFileName(d.toString())  + "\n";
                                            }
                                            else
                                                    newList += token + "\t" + token2 + "\t" + token3 + "\n";
                                    }
                                    Global.putFileOverwrite(mDBApi, "/" + user + "/lists.txt", newList);

                                    new itemListView(user, filename, mDBApi);                          
                                    setVisible(false);
                                    dispose();
                                }
                                else
                                    JOptionPane.showMessageDialog(this, "Item name is taken.");
  			}
  		}
    }//GEN-LAST:event_addItemButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JPanel addItemPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton canceladdItemButton;
    private javax.swing.JTextField categoryField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel newItemLabel;
    private javax.swing.JTextField storeField;
    private javax.swing.JLabel storeLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
    }
}
