/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addItemFrame.java
 *
 * Created on Apr 15, 2012, 2:09:33 AM
 */
package ibuyswing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.StringTokenizer;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.session.WebAuthSession;
import javax.swing.JOptionPane;
/**
 *
 * @author Luke
 */
public class addNewListFrame extends javax.swing.JFrame {

        private static DropboxAPI<WebAuthSession> mDBApi;
	private static String user;
        
    /** Creates new form addItemFrame */
    public addNewListFrame(String user, DropboxAPI<WebAuthSession> mDBApi) {
        
                super("iBuy - Add Item");
		this.user = user;
		this.mDBApi = mDBApi;
    
        initComponents();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newListPanel = new javax.swing.JPanel();
        newItemLabel = new javax.swing.JLabel();
        canceladdListButton = new javax.swing.JButton();
        addListButton = new javax.swing.JButton();
        newListTextField = new javax.swing.JTextField();
        newListLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(addNewListFrame.class);
        newListPanel.setBackground(resourceMap.getColor("newListPanel.background")); // NOI18N
        newListPanel.setName("newListPanel"); // NOI18N

        newItemLabel.setFont(resourceMap.getFont("newItemLabel.font")); // NOI18N
        newItemLabel.setForeground(resourceMap.getColor("newItemLabel.foreground")); // NOI18N
        newItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newItemLabel.setText(resourceMap.getString("newItemLabel.text")); // NOI18N
        newItemLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newItemLabel.setName("newItemLabel"); // NOI18N

        canceladdListButton.setBackground(resourceMap.getColor("canceladdListButton.background")); // NOI18N
        canceladdListButton.setFont(resourceMap.getFont("canceladdListButton.font")); // NOI18N
        canceladdListButton.setForeground(resourceMap.getColor("canceladdListButton.foreground")); // NOI18N
        canceladdListButton.setText(resourceMap.getString("canceladdListButton.text")); // NOI18N
        canceladdListButton.setActionCommand(resourceMap.getString("canceladdListButton.actionCommand")); // NOI18N
        canceladdListButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        canceladdListButton.setName("canceladdListButton"); // NOI18N
        canceladdListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceladdListButtonActionPerformed(evt);
            }
        });

        addListButton.setBackground(resourceMap.getColor("addListButton.background")); // NOI18N
        addListButton.setFont(resourceMap.getFont("addListButton.font")); // NOI18N
        addListButton.setForeground(resourceMap.getColor("addListButton.foreground")); // NOI18N
        addListButton.setText(resourceMap.getString("addListButton.text")); // NOI18N
        addListButton.setActionCommand(resourceMap.getString("addListButton.actionCommand")); // NOI18N
        addListButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        addListButton.setName("addListButton"); // NOI18N
        addListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addListButtonActionPerformed(evt);
            }
        });

        newListTextField.setFont(resourceMap.getFont("newListTextField.font")); // NOI18N
        newListTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newListTextField.setName("newListTextField"); // NOI18N

        newListLabel.setFont(resourceMap.getFont("newListLabel.font")); // NOI18N
        newListLabel.setForeground(resourceMap.getColor("newListLabel.foreground")); // NOI18N
        newListLabel.setText(resourceMap.getString("newListLabel.text")); // NOI18N
        newListLabel.setName("newListLabel"); // NOI18N

        javax.swing.GroupLayout newListPanelLayout = new javax.swing.GroupLayout(newListPanel);
        newListPanel.setLayout(newListPanelLayout);
        newListPanelLayout.setHorizontalGroup(
            newListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newListPanelLayout.createSequentialGroup()
                        .addGroup(newListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newItemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addGroup(newListPanelLayout.createSequentialGroup()
                                .addComponent(addListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(canceladdListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newListPanelLayout.createSequentialGroup()
                        .addComponent(newListLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newListTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        newListPanelLayout.setVerticalGroup(
            newListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(newListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newListTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newListLabel))
                .addGap(34, 34, 34)
                .addGroup(newListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canceladdListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newListPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newListPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-344)/2, (screenSize.height-260)/2, 344, 260);
    }// </editor-fold>//GEN-END:initComponents

    private void addListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListButtonActionPerformed
        if(evt.getSource() == addListButton)
  		{
			addList();
  		}
    }//GEN-LAST:event_addListButtonActionPerformed

    private void canceladdListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceladdListButtonActionPerformed
        if(evt.getSource() == canceladdListButton)
  		{
			new mainMenuFrame(user, mDBApi);
  			setVisible(false);
  			dispose();
  		}
    }//GEN-LAST:event_canceladdListButtonActionPerformed
public void addList()
	{
		String listName = newListTextField.getText();
		if(listName.equals(""))
			JOptionPane.showMessageDialog(this, "Please give new list a name.");
		else
		{
			String listFile = Global.getFile(mDBApi, "/" + user + "/lists.txt");
			StringTokenizer st = new StringTokenizer(listFile);
            boolean isTaken = false;
            while(st.hasMoreTokens())
            {
            	if(st.nextToken().equals(Global.toFileName(listName)))
            	{
            		isTaken = true;
            		break;
            	}
            	st.nextToken();
            	st.nextToken();
            }
            if(isTaken)
            {
                JOptionPane.showMessageDialog(this, "List name is taken.");  
            }
            else
            {
            	//Adds list to users list collection
            	listName = Global.toFileName(listName);
            	Date d = new Date(System.currentTimeMillis());
            	listFile += listName + "\t0.00\t" + Global.toFileName(d.toString()) + "\n";
            	Global.putFileOverwrite(mDBApi, "/" + user + "/lists.txt", listFile);
	        	
	        	//Creates new list
	        	Global.putFile(mDBApi, "/" + user + "/" + listName + ".txt", "");

	        	//Redirects to Main Menu
	        	new mainMenuFrame(user, mDBApi);
				setVisible(false);
	        	dispose();
            }
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addListButton;
    private javax.swing.JButton canceladdListButton;
    private javax.swing.JLabel newItemLabel;
    private javax.swing.JLabel newListLabel;
    private javax.swing.JPanel newListPanel;
    private javax.swing.JTextField newListTextField;
    // End of variables declaration//GEN-END:variables
}
