/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * createAccountFrame.java
 *
 * Created on Apr 10, 2012, 12:06:00 PM
 */
package ibuyswing;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.Date;
import java.util.StringTokenizer;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.DropboxAPI.DropboxFileInfo;
import com.dropbox.client2.DropboxAPI.Entry;
import com.dropbox.client2.exception.DropboxException;
import com.dropbox.client2.session.AccessTokenPair;
import com.dropbox.client2.session.AppKeyPair;
import com.dropbox.client2.session.RequestTokenPair;
import com.dropbox.client2.session.Session;
import com.dropbox.client2.session.WebAuthSession;
import javax.swing.JOptionPane;

/**
 * @author Luke
 */
public class createAccountFrame extends javax.swing.JFrame {

    private static DropboxAPI<WebAuthSession> mDBApi;
    /** Creates new form createAccountFrame */
    
    public createAccountFrame(DropboxAPI<WebAuthSession> mDBApi) {
        super("iBuy - Create An Account");
	this.mDBApi = mDBApi;
        initComponents();
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccountPanel = new javax.swing.JPanel();
        userNameField = new javax.swing.JTextField();
        UserNameLabel = new javax.swing.JLabel();
        passwordCreateLabel = new javax.swing.JLabel();
        confrimPasswordLabel = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        createAccountLabel = new javax.swing.JLabel();
        createAccountFeedBackLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(createAccountFrame.class);
        createAccountPanel.setBackground(resourceMap.getColor("createAccountPanel.background")); // NOI18N
        createAccountPanel.setName("createAccountPanel"); // NOI18N

        userNameField.setFont(resourceMap.getFont("userNameField.font")); // NOI18N
        userNameField.setToolTipText(resourceMap.getString("userNameField.toolTipText")); // NOI18N
        userNameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userNameField.setName("userNameField"); // NOI18N

        UserNameLabel.setFont(resourceMap.getFont("UserNameLabel.font")); // NOI18N
        UserNameLabel.setForeground(resourceMap.getColor("UserNameLabel.foreground")); // NOI18N
        UserNameLabel.setText(resourceMap.getString("UserNameLabel.text")); // NOI18N
        UserNameLabel.setName("UserNameLabel"); // NOI18N

        passwordCreateLabel.setFont(resourceMap.getFont("passwordCreateLabel.font")); // NOI18N
        passwordCreateLabel.setForeground(resourceMap.getColor("passwordCreateLabel.foreground")); // NOI18N
        passwordCreateLabel.setText(resourceMap.getString("passwordCreateLabel.text")); // NOI18N
        passwordCreateLabel.setName("passwordCreateLabel"); // NOI18N

        confrimPasswordLabel.setFont(resourceMap.getFont("confrimPasswordLabel.font")); // NOI18N
        confrimPasswordLabel.setForeground(resourceMap.getColor("confrimPasswordLabel.foreground")); // NOI18N
        confrimPasswordLabel.setText(resourceMap.getString("confrimPasswordLabel.text")); // NOI18N
        confrimPasswordLabel.setName("confrimPasswordLabel"); // NOI18N

        createButton.setBackground(resourceMap.getColor("createButton.background")); // NOI18N
        createButton.setFont(resourceMap.getFont("createButton.font")); // NOI18N
        createButton.setForeground(resourceMap.getColor("createButton.foreground")); // NOI18N
        createButton.setToolTipText(resourceMap.getString("createButton.toolTipText")); // NOI18N
        createButton.setActionCommand(resourceMap.getString("createButton.actionCommand")); // NOI18N
        createButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        createButton.setLabel(resourceMap.getString("createButton.label")); // NOI18N
        createButton.setName("createButton"); // NOI18N
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(resourceMap.getColor("cancelButton.background")); // NOI18N
        cancelButton.setFont(resourceMap.getFont("cancelButton.font")); // NOI18N
        cancelButton.setForeground(resourceMap.getColor("cancelButton.foreground")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setToolTipText(resourceMap.getString("cancelButton.toolTipText")); // NOI18N
        cancelButton.setActionCommand(resourceMap.getString("cancelButton.actionCommand")); // NOI18N
        cancelButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        cancelButton.setMaximumSize(new java.awt.Dimension(91, 33));
        cancelButton.setMinimumSize(new java.awt.Dimension(91, 33));
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        createAccountLabel.setFont(resourceMap.getFont("createAccountLabel.font")); // NOI18N
        createAccountLabel.setForeground(resourceMap.getColor("createAccountLabel.foreground")); // NOI18N
        createAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccountLabel.setText(resourceMap.getString("createAccountLabel.text")); // NOI18N
        createAccountLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAccountLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createAccountLabel.setName("createAccountLabel"); // NOI18N

        createAccountFeedBackLabel.setForeground(resourceMap.getColor("createAccountFeedBackLabel.foreground")); // NOI18N
        createAccountFeedBackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccountFeedBackLabel.setText(resourceMap.getString("createAccountFeedBackLabel.text")); // NOI18N
        createAccountFeedBackLabel.setName("createAccountFeedBackLabel"); // NOI18N

        passwordField.setFont(resourceMap.getFont("passwordField.font")); // NOI18N
        passwordField.setText(resourceMap.getString("passwordField.text")); // NOI18N
        passwordField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordField.setName("passwordField"); // NOI18N

        confirmPasswordField.setFont(resourceMap.getFont("confirmPasswordField.font")); // NOI18N
        confirmPasswordField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmPasswordField.setName("confirmPasswordField"); // NOI18N

        javax.swing.GroupLayout createAccountPanelLayout = new javax.swing.GroupLayout(createAccountPanel);
        createAccountPanel.setLayout(createAccountPanelLayout);
        createAccountPanelLayout.setHorizontalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordCreateLabel)
                    .addComponent(UserNameLabel)
                    .addComponent(confrimPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createAccountFeedBackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        createAccountPanelLayout.setVerticalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createAccountLabel)
                .addGap(58, 58, 58)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createAccountPanelLayout.createSequentialGroup()
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confrimPasswordLabel)))
                            .addComponent(passwordCreateLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPanelLayout.createSequentialGroup()
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameLabel))
                        .addGap(54, 54, 54)))
                .addGap(18, 18, 18)
                .addComponent(createAccountFeedBackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        userNameField.getAccessibleContext().setAccessibleName(resourceMap.getString("userNameField.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createAccountPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createAccountPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-404)/2, (screenSize.height-364)/2, 404, 364);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if(evt.getSource() == cancelButton){
            new logInFrame();
            setVisible(true);
            dispose();
                
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        if(evt.getSource() == createButton){
            signUp();
        }
    }//GEN-LAST:event_createButtonActionPerformed
    /**
     * @param args the command line arguments
     */  
    public void signUp()
	{
		String user = userNameField.getText();
		String pass = passwordField.getText();
		if(user.equals("") || pass.equals(""))
			JOptionPane.showMessageDialog(this, "Please complete all fields."); 
		else if (user.contains(" ") || pass.contains(" "))
		{
			JOptionPane.showMessageDialog(this, "No spaces, please.");
			String trimUser = "";
			String trimPass = "";
			for(int i = 0; i < user.length(); i++)
			{
				if(user.charAt(i) != ' ')
					trimUser += user.charAt(i);
			}
			for(int j = 0; j < user.length(); j++)
			{
				if(pass.charAt(j) != ' ')
					trimPass += pass.charAt(j);
			}
			userNameField.setText(trimUser);
			passwordField.setText(trimPass);
		}
		else
		{
			String usersFile = Global.getFile(mDBApi, "/users.txt");
			StringTokenizer scanner = new StringTokenizer(usersFile);
			boolean usernameIsTaken = false;
			while(scanner.hasMoreTokens())
			{
				String username = scanner.nextToken();
				String password = scanner.nextToken();
				if(username.equals(user))
				{
					usernameIsTaken = true;
				}
			}
			if(usernameIsTaken)
			{
				JOptionPane.showMessageDialog(this, "Username is taken. Please try another.");
			}
			else
			{
				//Adds user
				usersFile += user + "\t" + pass + "\n";
				Global.putFileOverwrite(mDBApi, "/users.txt", usersFile);
	        	
	        	//Create folder for user and first list
				Date d = new Date(System.currentTimeMillis());
				Global.makeFolder(mDBApi, "/" + user, "/" + user + "/lists.txt", "first_list\t 0.00\t" + Global.toFileName(d.toString()) + "\n");
	        	
	        	//Creates first list contents
	        	String firstList = "Apple\tFood\tGrocery\t1\tfalse\n" +
	        					   "Toilet_Paper\tPaper_Good\tGrocery\t3\ttrue\n";
	        	Global.putFile(mDBApi, "/" + user + "/first_list.txt", firstList);
	        	
	        	//Creates report options
	        	String report = "false\tfalse\tfalse\tfalse";
	        	Global.putFile(mDBApi, "/" + user + "/report.txt", report);
	        	
	        	//Redirect User to Menu
				new mainMenuFrame(user, mDBApi);
				setVisible(false);
                                dispose();
			}
		}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confrimPasswordLabel;
    private javax.swing.JLabel createAccountFeedBackLabel;
    private javax.swing.JLabel createAccountLabel;
    private javax.swing.JPanel createAccountPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel passwordCreateLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
